--- #YAML:1.0
name:                OpenOffice-UNO
version:             0.03
abstract:            interface to OpenOffice's UNO runtime
license:             open_source
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Bustamam Harun <bustamam@gmail.com>, Mattia Barbon <mbarbon@cpan.org>
